
 ; config_lion.ini

 dir_root = "D:/xampp/htdocs/xservice/reground_lt"
 
 db_host = "localhost"
 db_user = "root"
 db_pwd = "startend1@#$%"
 db_name = "lioncomp"

 benz_uid = "yy002"
 benz_pwd = "1235"

 